services:

  ledger-service:
    build:
      context: .
      dockerfile: Dockerfile.ledger
    ports:
      - "8081:8081"

  payments-service:
    build:
      context: .
      dockerfile: Dockerfile.payments
    ports:
      - "8080:8080"
    environment:
      - LEDGER_SERVICE_URL=http://ledger-service:8081
    depends_on:
      - ledger-service